"""Library browsing API — reports, tags, artifacts, search, stats."""

from __future__ import annotations

import json
from datetime import datetime
from pathlib import Path
from typing import Any

from fastapi import APIRouter, HTTPException, Query, Request
from fastapi.responses import FileResponse, PlainTextResponse
from pydantic import BaseModel, Field

from deep_research.citations import render_bibliography_markdown
from deep_research.config import AgentTopConfig
from deep_research.library.citation_archive import archive_cited_pdf
from deep_research.library.storage.base import StorageBackend
from deep_research.library.storage.rows import (
    AnalysisRow,
    ArtifactRow,
    CitationEdgeRow,
    GlossaryEntry,
    TagRow,
)
from deep_research.library.writer import LibraryWriter
from deep_research.llm.tool_loop import ToolRegistry
from deep_research.state import Citation
from deep_research.tools import arxiv as arxiv_tool
from deep_research.util import strip_arxiv_version
from deep_research.webui.deps import get_config, get_root_dir, get_storage
from deep_research.webui.format import citation_count, make_snippet, parse_citations
from deep_research.webui.models import (
    AnalysisInfo,
    ArtifactDetail,
    CitationEdgeInfo,
    DeleteReportResponse,
    GlossaryInfo,
    MergeReportsRequest,
    MergeReportsResponse,
    RenameReportRequest,
    ReportDetail,
    ReportListItem,
    ReportListResponse,
    SearchHitItem,
    SearchResponse,
    StatsResponse,
    TagInfo,
    TagUpdateResponse,
)

router = APIRouter(prefix="/api", tags=["library"])


class TagBody(BaseModel):
    tag: str = Field(min_length=1, max_length=64)


class ArxivPdfBody(BaseModel):
    arxiv_id: str = Field(min_length=3, max_length=64)


class ArxivPdfResponse(BaseModel):
    local_pdf_url: str | None = None
    archived: bool = False
    error: str | None = None


async def _report_items(backend: StorageBackend, reports) -> list[ReportListItem]:
    """Enrich report rows with tags, snippets, and PDF availability."""
    art_ids = [r.artifact_id for r in reports if r.artifact_id]
    tags_map = await backend.get_tags_for_artifacts(art_ids)
    artifacts_map = await backend.get_artifacts(art_ids)
    items: list[ReportListItem] = []
    for r in reports:
        art = artifacts_map.get(r.artifact_id or "")
        items.append(
            ReportListItem(
                run_id=r.run_id,
                started_at=r.started_at,
                completed_at=r.completed_at,
                query=r.original_query,
                path=r.path_taken,
                iterations=r.iterations,
                tags=sorted(t.tag for t in tags_map.get(r.artifact_id, [])),
                snippet=make_snippet(r.markdown),
                citation_count=citation_count(r.citations_json),
                markdown_length=len(r.markdown),
                has_pdf=bool(art and art.kind == "pdf" and art.bytes_path),
            )
        )
    return items


def _parse_json_list(raw: str | None) -> list[str]:
    if not raw:
        return []
    try:
        data = json.loads(raw)
    except (json.JSONDecodeError, TypeError):
        return []
    return [str(x) for x in data] if isinstance(data, list) else []


def _glossary_info(e: GlossaryEntry) -> GlossaryInfo:
    return GlossaryInfo(
        term=e.term,
        term_canonical=e.term_canonical,
        kind=e.kind,
        short_def=e.short_def,
        long_def=e.long_def,
        acronym_expansion=e.acronym_expansion,
        related_terms=_parse_json_list(e.related_terms),
        domain_tags=_parse_json_list(e.domain_tags),
        confidence=e.confidence,
        first_seen_run_id=e.first_seen_run_id,
        first_seen_artifact_id=e.first_seen_artifact_id,
        last_updated=e.last_updated,
    )


async def _report_glossary(backend: StorageBackend, run_id: str) -> list[GlossaryInfo]:
    """Glossary entries attributed to a report (terms first seen in its run)."""
    entries = await backend.list_glossary_entries()
    return [_glossary_info(e) for e in entries if e.first_seen_run_id == run_id]


def _render_citations_bib(citations: list[Citation]) -> str:
    """Emit a .bib file for the report's citations."""
    entries: list[str] = []
    for i, c in enumerate(citations, start=1):
        title = _bib_escape(c.title or c.url or "Untitled")
        authors = " and ".join(c.authors) if c.authors else "Anonymous"
        url = _bib_escape(c.url or "")
        doi = _bib_escape(c.doi or "") if c.doi else ""
        lines = [f"@misc{{cite{i},\n", f"  title = {{{title}}},\n", f"  author = {{{authors}}},\n"]
        if doi:
            lines.append(f"  doi = {{{doi}}},\n")
        lines.append(f"  url = {{{url}}},\n")
        lines.append(f"  year = {{{c.year or 'unknown'}}}\n")
        lines.append("}\n")
        entries.append("".join(lines))
    return "% Generated by deep-research web UI\n" + "".join(entries)


def _bib_escape(s: str) -> str:
    return s.replace("{", "\\{").replace("}", "\\}")


def _citations_objects(citations: list[dict[str, Any]]) -> list[Citation]:
    """Map stored citation dicts to Citation objects for rendering."""
    out: list[Citation] = []
    for c in citations:
        try:
            out.append(Citation.model_validate(c))
        except Exception:
            continue
    return out


def _analysis_info(a: AnalysisRow) -> AnalysisInfo:
    return AnalysisInfo(
        analysis_id=a.analysis_id,
        artifact_id=a.artifact_id,
        run_id=a.run_id,
        analyzer=a.analyzer,
        summary=a.summary,
        key_findings=_parse_json_list(a.key_findings),
        methodology=a.methodology,
        limitations=a.limitations,
        gaps=a.gaps,
        follow_ups=a.follow_ups,
        key_references=_parse_json_list(a.key_references),
        relevance_to_query=a.relevance_to_query,
        analyzed_at=a.analyzed_at,
    )


def _edge_info(e: CitationEdgeRow) -> CitationEdgeInfo:
    return CitationEdgeInfo(
        source_artifact_id=e.source_artifact_id,
        target_artifact_id=e.target_artifact_id,
        target_arxiv_id=e.target_arxiv_id,
        rationale=e.rationale,
        weight=e.weight,
        discovered_in_run=e.discovered_in_run,
    )


def _strip_arxiv_version(arxiv_id: str) -> str:
    """Normalize 2401.12345v2 -> 2401.12345 for artifact lookups."""
    return strip_arxiv_version(arxiv_id)


async def _citation_artifact(
    backend: StorageBackend,
    citation: dict[str, Any],
) -> ArtifactRow | None:
    """Find the locally archived artifact for a citation, if any.

    Looks up by arxiv_id first (academic path keys PDFs that way), then by the
    citation's URL (the HTML/blog archive seam stores source_url on every
    artifact). Returns the artifact regardless of kind so callers can decide
    what to expose.
    """
    aid = citation.get("arxiv_id")
    artifact: ArtifactRow | None = None
    if isinstance(aid, str) and aid and not aid.startswith("scholar:"):
        artifact = await backend.find_artifact_by_arxiv_id(_strip_arxiv_version(aid))
    if artifact is None:
        url = citation.get("url")
        if isinstance(url, str) and url.startswith(("http://", "https://")):
            artifact = await backend.find_artifact_by_url(url)
    return artifact


def _artifact_file_route(root: Path, artifact: ArtifactRow, route: str) -> str | None:
    """Return the API route for *artifact*'s file if it exists on disk, else None."""
    root_resolved = root.resolve()
    file_path = (root_resolved / artifact.bytes_path).resolve()
    if not file_path.is_relative_to(root_resolved) or not file_path.is_file():
        return None
    return route


async def _citation_local_pdf_url(
    backend: StorageBackend,
    root: Path,
    citation: dict[str, Any],
) -> str | None:
    """Return a URL for the locally archived PDF of this citation, if any.

    Papers archived by the academic path are stored as `kind="pdf"` artifacts
    keyed by arxiv_id (and source_url), so references can open the library's
    own copy instead of the upstream page.
    """
    artifact = await _citation_artifact(backend, citation)
    if artifact is None or artifact.kind != "pdf" or not artifact.bytes_path:
        return None
    return _artifact_file_route(root, artifact, f"/api/artifacts/{artifact.artifact_id}/pdf")


async def _citation_local_image_url(
    backend: StorageBackend,
    root: Path,
    citation: dict[str, Any],
) -> str | None:
    """Return a URL for the locally archived screenshot of this citation, if any.

    HTML/blog sources whose PDF render failed are archived as `kind="image"`
    screenshots, so references can open the library's own copy.
    """
    artifact = await _citation_artifact(backend, citation)
    if artifact is None or artifact.kind != "image" or not artifact.bytes_path:
        return None
    return _artifact_file_route(root, artifact, f"/api/artifacts/{artifact.artifact_id}/image")


async def _enrich_citations(
    backend: StorageBackend,
    root: Path,
    citations_json: str | None,
) -> list[dict[str, Any]]:
    """Attach `local_pdf_url` / `local_image_url` to citations that have an
    archived PDF or screenshot copy."""
    citations = parse_citations(citations_json)
    for c in citations:
        local_pdf = await _citation_local_pdf_url(backend, root, c)
        if local_pdf:
            c["local_pdf_url"] = local_pdf
        else:
            local_image = await _citation_local_image_url(backend, root, c)
            if local_image:
                c["local_image_url"] = local_image
    return citations


async def _require_report_artifact(backend: StorageBackend, run_id: str) -> str:
    report = await backend.get_report(run_id)
    if report is None:
        raise HTTPException(status_code=404, detail="report not found")
    if not report.artifact_id:
        raise HTTPException(status_code=400, detail="report has no artifact; cannot manage tags")
    return report.artifact_id


@router.get("/health")
async def health() -> dict[str, str]:
    return {"status": "ok"}


@router.get("/reports", response_model=ReportListResponse)
async def list_reports(
    request: Request,
    limit: int = Query(50, ge=1, le=200),
    offset: int = Query(0, ge=0),
    q: str | None = Query(None, min_length=1, max_length=200),
    tag: str | None = Query(None, max_length=64),
    path: str | None = Query(None, max_length=32),
) -> ReportListResponse:
    backend = get_storage(request)
    if q:
        reports = await backend.search_reports(q, limit=limit, offset=offset, tag=tag, path=path)
        total = await backend.count_reports(q=q, tag=tag, path=path)
    else:
        reports = await backend.list_reports(limit=limit, offset=offset, tag=tag, path=path)
        total = await backend.count_reports(tag=tag, path=path)
    items = await _report_items(backend, reports)
    return ReportListResponse(total=total, limit=limit, offset=offset, items=items)


@router.get("/reports/{run_id}", response_model=ReportDetail)
async def get_report_detail(run_id: str, request: Request) -> ReportDetail:
    backend = get_storage(request)
    report = await backend.get_report(run_id)
    if report is None:
        raise HTTPException(status_code=404, detail="report not found")
    tags: list[str] = []
    artifact: ArtifactRow | None = None
    if report.artifact_id:
        artifact = await backend.get_artifact(report.artifact_id)
        tag_rows = await backend.get_tags_for_artifact(report.artifact_id)
        tags = sorted(t.tag for t in tag_rows)
    has_pdf = bool(artifact and artifact.kind == "pdf" and artifact.bytes_path)
    return ReportDetail(
        run_id=report.run_id,
        started_at=report.started_at,
        completed_at=report.completed_at,
        query=report.original_query,
        path=report.path_taken,
        classifier_rationale=report.classifier_rationale,
        iterations=report.iterations,
        markdown=report.markdown,
        citations=await _enrich_citations(backend, get_root_dir(request), report.citations_json),
        tags=tags,
        artifact_id=report.artifact_id,
        has_pdf=has_pdf,
        pdf_url=f"/api/reports/{run_id}/pdf" if has_pdf else None,
        markdown_url=f"/api/reports/{run_id}/markdown",
        glossary=await _report_glossary(backend, run_id),
        glossary_url=f"/api/reports/{run_id}/glossary/markdown",
        bibliography_url=f"/api/reports/{run_id}/bibliography",
        bibliography_bib_url=f"/api/reports/{run_id}/bibliography/bib",
    )


@router.get("/reports/{run_id}/markdown")
async def get_report_markdown(run_id: str, request: Request) -> PlainTextResponse:
    backend = get_storage(request)
    report = await backend.get_report(run_id)
    if report is None:
        raise HTTPException(status_code=404, detail="report not found")
    return PlainTextResponse(
        report.markdown,
        media_type="text/markdown; charset=utf-8",
        headers={"Content-Disposition": f'inline; filename="{run_id}.md"'},
    )


def _render_glossary_markdown(glossary: list[GlossaryInfo]) -> str:
    """Render the glossary entries as a markdown section (downloadable)."""
    if not glossary:
        return "# Glossary\n\n_No glossary terms recorded for this report._\n"
    lines = ["# Glossary", ""]
    for g in sorted(glossary, key=lambda x: x.term_canonical):
        lines.append(f"## {g.term}")
        if g.acronym_expansion:
            lines.append(f"_({g.acronym_expansion})_")
        if g.short_def:
            lines.append("")
            lines.append(g.short_def)
        if g.long_def:
            lines.append("")
            lines.append(g.long_def)
        if g.related_terms:
            lines.append("")
            lines.append(f"Related: {', '.join(g.related_terms)}")
        if g.domain_tags:
            lines.append(f"Tags: {', '.join(g.domain_tags)}")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


@router.get("/reports/{run_id}/glossary/markdown")
async def get_report_glossary_markdown(run_id: str, request: Request) -> PlainTextResponse:
    backend = get_storage(request)
    report = await backend.get_report(run_id)
    if report is None:
        raise HTTPException(status_code=404, detail="report not found")
    md = _render_glossary_markdown(await _report_glossary(backend, run_id))
    return PlainTextResponse(
        md,
        media_type="text/markdown; charset=utf-8",
        headers={"Content-Disposition": f'attachment; filename="{run_id}-glossary.md"'},
    )


@router.get("/reports/{run_id}/bibliography")
async def get_report_bibliography(run_id: str, request: Request) -> PlainTextResponse:
    backend = get_storage(request)
    report = await backend.get_report(run_id)
    if report is None:
        raise HTTPException(status_code=404, detail="report not found")
    bib_md = render_bibliography_markdown(
        _citations_objects(parse_citations(report.citations_json))
    )
    if not bib_md:
        bib_md = "## Bibliography\n\n_No cited sources recorded for this report._\n"
    return PlainTextResponse(
        bib_md,
        media_type="text/markdown; charset=utf-8",
        headers={"Content-Disposition": f'attachment; filename="{run_id}-bibliography.md"'},
    )


@router.get("/reports/{run_id}/bibliography/bib")
async def get_report_bibliography_bib(run_id: str, request: Request) -> PlainTextResponse:
    backend = get_storage(request)
    report = await backend.get_report(run_id)
    if report is None:
        raise HTTPException(status_code=404, detail="report not found")
    bib = _render_citations_bib(_citations_objects(parse_citations(report.citations_json)))
    if not bib.strip():
        bib = "% No cited sources recorded for this report.\n"
    return PlainTextResponse(
        bib,
        media_type="application/x-bibtex; charset=utf-8",
        headers={"Content-Disposition": f'attachment; filename="{run_id}.bib"'},
    )


@router.get("/reports/{run_id}/pdf")
async def get_report_pdf(run_id: str, request: Request) -> FileResponse:
    backend = get_storage(request)
    root = get_root_dir(request)
    report = await backend.get_report(run_id)
    if report is None:
        raise HTTPException(status_code=404, detail="report not found")
    artifact = await backend.get_artifact(report.artifact_id) if report.artifact_id else None
    if artifact is None or artifact.kind != "pdf" or not artifact.bytes_path:
        raise HTTPException(status_code=404, detail="no archived PDF for this report")
    root_resolved = root.resolve()
    file_path = (root_resolved / artifact.bytes_path).resolve()
    if not file_path.is_relative_to(root_resolved) or not file_path.is_file():
        raise HTTPException(status_code=404, detail="archived PDF file missing")
    return FileResponse(file_path, media_type="application/pdf", filename=f"{run_id}.pdf")


@router.get("/artifacts/{artifact_id}/pdf")
async def get_artifact_pdf(artifact_id: str, request: Request) -> FileResponse:
    """Serve an archived PDF artifact (e.g. a paper PDF stored by the academic path)."""
    backend = get_storage(request)
    root = get_root_dir(request)
    artifact = await backend.get_artifact(artifact_id)
    if artifact is None or artifact.kind != "pdf" or not artifact.bytes_path:
        raise HTTPException(status_code=404, detail="no archived PDF for this artifact")
    root_resolved = root.resolve()
    file_path = (root_resolved / artifact.bytes_path).resolve()
    if not file_path.is_relative_to(root_resolved) or not file_path.is_file():
        raise HTTPException(status_code=404, detail="archived PDF file missing")
    return FileResponse(
        file_path, media_type="application/pdf", filename=f"{artifact.artifact_id}.pdf"
    )


@router.get("/artifacts/{artifact_id}/image")
async def get_artifact_image(artifact_id: str, request: Request) -> FileResponse:
    """Serve an archived webpage-screenshot image artifact (kind="image")."""
    backend = get_storage(request)
    root = get_root_dir(request)
    artifact = await backend.get_artifact(artifact_id)
    if artifact is None or artifact.kind != "image" or not artifact.bytes_path:
        raise HTTPException(status_code=404, detail="no archived image for this artifact")
    root_resolved = root.resolve()
    file_path = (root_resolved / artifact.bytes_path).resolve()
    if not file_path.is_relative_to(root_resolved) or not file_path.is_file():
        raise HTTPException(status_code=404, detail="archived image file missing")
    return FileResponse(
        file_path,
        media_type="image/png",
        filename=f"{artifact.artifact_id}.png",
    )


@router.post("/arxiv/pdf", response_model=ArxivPdfResponse)
async def archive_cited_arxiv_pdf(body: ArxivPdfBody, request: Request) -> ArxivPdfResponse:
    """On-demand: download + archive one arXiv paper PDF from a reference card."""
    backend = get_storage(request)
    root = get_root_dir(request)
    cfg: AgentTopConfig = get_config(request)
    aid = body.arxiv_id.strip()
    base = strip_arxiv_version(aid)
    if not base or base.startswith("scholar:"):
        raise HTTPException(status_code=422, detail="invalid arxiv id")

    existing = await backend.find_artifact_by_arxiv_id(base)
    if existing is not None and existing.kind == "pdf" and existing.bytes_path:
        return ArxivPdfResponse(local_pdf_url=f"/api/artifacts/{existing.artifact_id}/pdf")

    if not cfg.arxiv.enabled or not cfg.arxiv.download_pdfs:
        return ArxivPdfResponse(error="arxiv pdf downloads are disabled in config")

    reg = ToolRegistry()
    try:
        await arxiv_tool.register(reg, cfg)
        writer = LibraryWriter(backend, str(root))
        artifact_id = await archive_cited_pdf(aid, title=None, tools=reg, writer=writer)
    finally:
        await reg.close()

    if not artifact_id:
        return ArxivPdfResponse(error="download failed - paper may not be open access")
    return ArxivPdfResponse(local_pdf_url=f"/api/artifacts/{artifact_id}/pdf", archived=True)


@router.post("/reports/{run_id}/tags", response_model=TagUpdateResponse)
async def add_report_tag(run_id: str, body: TagBody, request: Request) -> TagUpdateResponse:
    backend = get_storage(request)
    artifact_id = await _require_report_artifact(backend, run_id)
    tag = body.tag.strip()
    if not tag:
        raise HTTPException(status_code=422, detail="tag cannot be blank")
    await backend.upsert_tag(TagRow(tag=tag, artifact_id=artifact_id, applied_in_run=None))
    rows = await backend.get_tags_for_artifact(artifact_id)
    return TagUpdateResponse(tags=sorted(t.tag for t in rows))


@router.delete("/reports/{run_id}/tags", response_model=TagUpdateResponse)
async def remove_report_tag(
    run_id: str,
    request: Request,
    tag: str = Query(..., min_length=1, max_length=64),
) -> TagUpdateResponse:
    backend = get_storage(request)
    artifact_id = await _require_report_artifact(backend, run_id)
    await backend.delete_tag(tag.strip(), artifact_id)
    rows = await backend.get_tags_for_artifact(artifact_id)
    return TagUpdateResponse(tags=sorted(t.tag for t in rows))


@router.delete("/reports/{run_id}", response_model=DeleteReportResponse)
async def delete_report(
    run_id: str,
    request: Request,
    confirm: bool = Query(False),
) -> DeleteReportResponse:
    if not confirm:
        raise HTTPException(status_code=400, detail="confirm=true is required to delete a report")
    backend = get_storage(request)
    root = get_root_dir(request)
    report = await backend.get_report(run_id)
    if report is None:
        raise HTTPException(status_code=404, detail="report not found")
    removed: list[str] = []
    date_str = report.completed_at or report.started_at
    if date_str:
        try:
            dt = datetime.fromisoformat(date_str)
            day_dir = root / "reports" / f"{dt.year}" / f"{dt.month:02d}" / f"{dt.day:02d}"
            for suffix in (".md", ".pdf"):
                candidate = day_dir / f"{run_id}{suffix}"
                if candidate.exists():
                    candidate.unlink()
                    removed.append(str(candidate))
        except ValueError:
            pass
    await backend.delete_report(run_id)
    return DeleteReportResponse(removed_files=removed)


@router.patch("/reports/{run_id}", response_model=ReportDetail)
async def rename_report(run_id: str, body: RenameReportRequest, request: Request) -> ReportDetail:
    """Rename a research report (updates its display name/title)."""
    backend = get_storage(request)
    report = await backend.get_report(run_id)
    if report is None:
        raise HTTPException(status_code=404, detail="report not found")
    await backend.rename_report(run_id, body.query.strip())
    return await get_report_detail(run_id, request)


@router.post("/reports/{run_id}/merge", response_model=MergeReportsResponse)
async def merge_report(
    run_id: str, body: MergeReportsRequest, request: Request
) -> MergeReportsResponse:
    """Merge this report with the given others into one unified report.

    Runs inline (a single LLM call). Returns the new merged report's run_id.
    """
    backend = get_storage(request)
    cfg = get_config(request)
    root = get_root_dir(request)

    all_ids = list(dict.fromkeys([run_id] + [x.strip() for x in body.other_run_ids if x.strip()]))
    if len(all_ids) < 2:
        raise HTTPException(status_code=422, detail="merge requires at least two distinct reports")
    for rid in all_ids:
        if await backend.get_report(rid) is None:
            raise HTTPException(status_code=404, detail=f"report not found: {rid}")

    from deep_research.library.merge import merge_reports
    from deep_research.library.writer import LibraryWriter
    from deep_research.llm.router import LLMRouter

    writer = LibraryWriter(backend, str(root))
    try:
        async with LLMRouter(cfg.llm) as router:
            new_run_id = await merge_reports(
                backend,
                writer,
                all_ids,
                router,
                name=body.name,
                delete_sources=body.delete_sources,
            )
    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e))
    new_report = await backend.get_report(new_run_id)
    return MergeReportsResponse(
        run_id=new_run_id,
        query=(new_report.original_query if new_report else "") or "",
    )


@router.get("/tags", response_model=list[TagInfo])
async def list_tags(
    request: Request,
    limit: int = Query(200, ge=1, le=1000),
) -> list[TagInfo]:
    backend = get_storage(request)
    rows = await backend.list_tags(limit=limit)
    return [TagInfo(tag=t, count=c) for t, c in rows]


@router.get("/artifacts/{artifact_id}", response_model=ArtifactDetail)
async def get_artifact_detail(artifact_id: str, request: Request) -> ArtifactDetail:
    backend = get_storage(request)
    artifact = await backend.get_artifact(artifact_id)
    if artifact is None:
        raise HTTPException(status_code=404, detail="artifact not found")
    analyses = await backend.get_analyses_for_artifact(artifact_id)
    edges = await backend.get_citation_edges_for_source(artifact_id)
    tag_rows = await backend.get_tags_for_artifact(artifact_id)
    return ArtifactDetail(
        artifact_id=artifact.artifact_id,
        kind=artifact.kind,
        source_url=artifact.source_url,
        source_type=artifact.source_type,
        title=artifact.title,
        image_url=(
            f"/api/artifacts/{artifact.artifact_id}/image" if artifact.kind == "image" else None
        ),
        authors=_parse_json_list(artifact.authors),
        arxiv_id=artifact.arxiv_id,
        bytes_path=artifact.bytes_path,
        bytes_size=artifact.bytes_size,
        first_seen_at=artifact.first_seen_at,
        last_touched_at=artifact.last_touched_at,
        tags=sorted(t.tag for t in tag_rows),
        analyses=[_analysis_info(a) for a in analyses],
        citation_edges=[_edge_info(e) for e in edges],
    )


@router.get("/search", response_model=SearchResponse)
async def search(
    request: Request,
    q: str = Query(..., min_length=1, max_length=200),
    limit: int = Query(20, ge=1, le=100),
) -> SearchResponse:
    backend = get_storage(request)
    reports = await backend.search_reports(q, limit=limit, offset=0)
    items = await _report_items(backend, reports)
    hits = await backend.full_text_search(q, kind="any", limit=limit)
    return SearchResponse(
        q=q,
        reports=items,
        artifacts=[
            SearchHitItem(
                artifact_id=h.artifact_id,
                title=h.title,
                authors=h.authors,
                summary=h.summary,
                score=h.score,
            )
            for h in hits
        ],
    )


@router.get("/stats", response_model=StatsResponse)
async def stats(request: Request) -> StatsResponse:
    backend = get_storage(request)
    return StatsResponse(
        reports=await backend.count_reports(),
        artifacts=await backend.count_artifacts(),
        tags=len(await backend.list_tags(limit=100000)),
    )
